### ISSUE TITLE
Code Credits

### ISSUE THREAD

**Issue by yehia-mamdouh** [UltimateHackers/XSSight#1]
Hi Fake UltimateHackers,

I have seen your tool XSSight - nice one - but when you copy and paste more than 60 % of my tool code XSSYA the ethics is take a permission from me or at least give me a proper credit or mention that you copy paste more than 60% of tool code or give thanks to me - um still looking for the rest 40% and from where you copied it and by then i will make you regret doing what you did. 
https://github.com/yehia-mamdouh/XSSYA 
No Thanks

**Comment by UltimateHackers** [comment]
Credits given.
Check the the script and our blog post http://teamultimate.in/xssight-xss-scanner-payload-injector-d3v/
